### ISSUE TITLE
EOL Push Jobs in Workstation

### ISSUE THREAD

**Issue by tas50** [chef/chef-workstation#1610]
Push Jobs goes EOL 12/31/2020 and we need to plan out the removal of Push Jobs functionally from Workstation:

- [x] Remove Push Jobs from the Workstation packages
- [x] Update all documentation to remove reference to Push Jobs except for content in the "Legacy" section
- [x] Add EOL notices to push jobs repositories
- [x] Move the push jobs repositories to the Chef Boneyard
- [x] Release Chef Workstation without Push Jobs

**Comment by ramereth** [comment]
Looks like #1608 resolved this or am I wrong?

**Comment by tas50** [comment]
There's still a few more steps above to complete.

**Comment by tas50** [comment]
Almost there!
