### ISSUE TITLE
The road to 1.0

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-workstation#535]
TODO 

## Motivation

As a Chef Workstation user,
I want to know that I am using a released product,
so that I receive new development and bug fixes that a beta product does not imply.

## Specification

We have said that we want to move users from the ChefDK to Chef Workstation. In order to do that we need to release 1.0 because our enterprise users will not use a 'beta' product.

This card is meant to start tracking the work needed to get us to that place.

- [ ] Craft a message about deprecating ChefDK and publish that. Will we release a ChefDK 5.0? Move workstation from 0.9 to 5.0? 
- [ ] What is our versioning plan? We specifically don't want to use SemVer for a CLI tool because it is meant to be consumed by users.
- [ ] Customers have asked for an 18 month deprecation cycle. How do we handle releasing breaking changes (to bring them onto a new workflow) without breaking their existing workflows? We need to seperate what is meant to be used by users and what is meant to be used by CI.
- [ ] What work is planned for a unified CLI? How are we going to cause minimal impact to customers when we change the `chef` commands?
- [ ] https://github.com/chef/chef-workstation/issues/536

## Downstream Impact

TODO 

Aha! Link: https://chef.aha.io/features/SH-1744

**Comment by tas50** [comment]
We shipped 1.0 a while ago
